spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
        
---

spring:
  profiles: staging
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
        
---
        
spring:
  profiles: production
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ulock-postgres.weave.local/ulock
    username: postgres
    password: ${DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update
        
