spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    jpa:
      hibernate:
        ddl-auto: create
        
keycloak:
  realm:  ulock
  realmKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjnk/6TG4JKf5bMFCXrHseoQ/4R3rgNMWnhaWsQ464KetOPRvs5QEXb8TUCziBsvPpzfEu2l0BFPcKfp9GIAwQUwcWvJMh5AZ3JzTWaje10zfWeCVutVdwlr7VRIFBBosMtn+gIigsGzcZSx60IS4c+h+NNn3jRmJQz83/YmpchMwEdA8M49CMw2jXbhDNFtDotID1Ge2pXkU9stcEwPzlLIr8loD33MRKcraN2y7ERLMPJPzGBxWwYvmJOKZb2p/sa5KJjHE2nRarZCli9CcksAaOgZXKhYNtzq01c+zINa+iAgqCIDzIxlxaKkxUvd1L/41TlnbLLQdgQHz7m5CowIDAQAB
  bearer-only: true
  auth-server-url: https://accounts.ulock.co/auth
  ssl-required: external
  resource: ulock-api
  securityConstraints:
    - securityCollections:
        - name: api
          authRoles: user
          patterns: /
  
